### ISSUE TITLE
typedef in ThriftSpec not handled correctly in zanzibar

### ISSUE THREAD

**Issue by stevededalus** [uber/zanzibar#137]
typedef Thrift aliases are treated as custom types in the compiled.Field golang structs instead of as at the underlying type. This breaks code generation.

A common pattern is alias UUID as strings and returning lists of UUIDs and maps keyed by UUIDs. Code generation in zanzibar breaks because it does not understand the UUID fields are string types.

**Comment by Raynos** [comment]
Another example of this is strings backed by query parameters or headers when using a UUID typedef. We do not generate code that casts the string to the typedef correctly.
