### ISSUE TITLE
Make generate does not remove obselete files generated by easyjson

### ISSUE THREAD

**Issue by ChuntaoLu** [uber/zanzibar#149]
Reproduce steps:
1. add a new method to a thrift file;
2. `make generate` and commit changes;
3. removes the method in step 1 from the thrift file;
4. `make generate` and the esayjson files are still present.

**Comment by Raynos** [comment]
Correct. obsolute things are not removed.

This is why we have a check `https://github.com/uber/zanzibar/blob/master/Makefile#L91-L97`

I dont know how to automate the removal without removing the caching.

**Comment by ChuntaoLu** [comment]
ok, I guess we can live with `make check-generate`.
