### ISSUE TITLE
Don't rely on dev branches

### ISSUE THREAD

**Issue by abhinav** [uber/zanzibar#167]
Hi,

Please stop relying on development branches of ThriftRW Go. If it's not on
master, you shouldn't be relying on it. If you need a feature from a
development branch, please work with us to get it merged into master.

Context: https://github.com/thriftrw/thriftrw-go/pull/305#issuecomment-316937905

CC @breerly @blampe @Raynos @ChuntaoLu

**Comment by Raynos** [comment]
We forgot to get the branch merged, will upgrade to master soon.

**Comment by abhinav** [comment]
Hey, as discussed offline, that branch is getting deleted this Friday.

**Comment by abhinav** [comment]
Deleted as discussed.

**Comment by ChuntaoLu** [comment]
This has been fixed since https://github.com/uber/zanzibar/pull/202
