### ISSUE TITLE
Resque alike workerpool with redis(?) to queue up repo update jobs instead of lock

### ISSUE THREAD

**Issue by cl1337** [uber/zanzibar#293]
currently updating files in repo cannot scale with multiple users with high update traffic, we'd like to implement a workerpool and redis to back jobs exec, this should support us with the growth of use in next 6 months

**Comment by Raynos** [comment]
Have you tried allocating multiple temp folder and writing to them in parallel :rofl:

**Comment by cl1337** [comment]
as discussed today, yes :) I would explore this option
