### ISSUE TITLE
Test hangs when a stdout print is added to a client initializer

### ISSUE THREAD

**Issue by ChuntaoLu** [uber/zanzibar#302]
Reproduce steps:
1. add `fmt.Println("test")` in [here](https://github.com/uber/zanzibar/blob/master/examples/example-gateway/build/clients/bar/bar.go#L211).
2. run test [bar_bar_method_argnotstruct_test.go](https://github.com/uber/zanzibar/blob/master/examples/example-gateway/build/endpoints/bar/bar_bar_method_argnotstruct_test.go).
3. test process hangs

I suspect it has something to do with how the child process test gateway works.

**Comment by Raynos** [comment]
https://github.com/uber/zanzibar/blob/master/test/lib/test_gateway/test_gateway_process.go#L150

The test framework assumes that the first log line from the logger is "starting the server" with information about the port.

This method `readAddrFromStdout` needs to be refactored to loop/search through all of the logs until it find the "starting the server" logline. 

Adding a timeout to the `readAddrFromStdout` method also resolves the hanging problem.
