### ISSUE TITLE
goimports invoked directly rather than through go run

### ISSUE THREAD

**Issue by jacobgreenleaf** [uber/zanzibar#343]
goimports is [invoked](https://github.com/uber/zanzibar/blob/f666616ed4ea25cecbdffffa776e53ee57fa175b/codegen/module.go#L972) using system call rather than `go run`, which creates an implicit dependency on goimports. It should at least be invoked using `go run` on the source code, if not invoked against the code.

**Comment by ChuntaoLu** [comment]
Should we have explicit dependency on `goimports`? Otherwise what alternative do you have in mind?

**Comment by jacobgreenleaf** [comment]
`goimports` is not distributed with Go:

```
$ ls -l /usr/local/Cellar/go/1.10.1/bin/
total 0
lrwxr-xr-x  1 jacobg  admin  17 Mar 28 21:28 go -> ../libexec/bin/go
lrwxr-xr-x  1 jacobg  admin  20 Mar 28 21:28 godoc -> ../libexec/bin/godoc
lrwxr-xr-x  1 jacobg  admin  20 Mar 28 21:28 gofmt -> ../libexec/bin/gofmt
```

It's packaged as `golang.org/x/tools/cmd/goimports`. We depend on this special `Makefile` target:

```
.PHONY: install
install:
    # [...]
    @goimports -h 2>/dev/null || go get golang.org/x/tools/cmd/goimports
```

So while we're enforcing that the implicit dependency is met, it's still uncontrolled by version control, and also manipulates the developer's GOPATH environment which is less than ideal. Ideally we would use a single tool for managing dependencies (currently glide) rather than two (`go get` for some developer tools, glide for others).
