### ISSUE TITLE
easy json generate only works for http endpoint

### ISSUE THREAD

**Issue by cl1337** [uber/zanzibar#393]
https://github.com/uber/zanzibar/blob/master/codegen/runner/pre-steps.sh#L92
hardcoded check to bypass non `http` endpoint, we might want this to be configured from a list of endpoints that want to use easy-json

**Comment by ChuntaoLu** [comment]
Easyjson generated JSON (un)marshallers should be only used on endpoints that use JSON (de)serialization, which is the case for http endpoints. We probably won't support JSON (de)serialization for non-http protocols.
