### ISSUE TITLE
pinned linter to a specific version in vendor/

### ISSUE THREAD

**Issue by cl1337** [uber/zanzibar#398]
pin `honnef.co/go/tools/cmd/staticcheck` to `8ed405e85c65fb38745a8eafe01ee9590523f172 `
in https://github.com/uber/zanzibar/pull/397

lastest master of this linter is grumpy about 
https://golang.org/pkg/fmt/#Fprintln returned error is not checked in generated easy_json go files

Another thought, ideally we don't need pin linter, `in linter we trust` if we commit to a linter our code repo should evolve style with it, otherwise what could happen is 1 year from now no one bothers to bump this and we missed some important linting rules provided, I'm open to either way

**Comment by jacobgreenleaf** [comment]
#341 #343 

note: We should still use glide to manage the linter, but ideally pin to master rather than specific hash.
