### ISSUE TITLE
Too many parameters in packageHelper constructor

### ISSUE THREAD

**Issue by ChuntaoLu** [uber/zanzibar#418]
https://github.com/uber/zanzibar/blob/master/codegen/package.go#L63 takes a lot of parameters, and packageHelper becomes a common dump ground for many different things. We should refactor the params into a struct to avoid frequent constructor signature change.

**Comment by cl1337** [comment]
[option params](https://github.com/yarpc/yarpc-go/blob/20285154bf8dd8976d3202fb0adc3000d4be705f/transport/grpc/options.go) seems like a good practice
