### ISSUE TITLE
Pack the zanzibar-defaults config into the binary

### ISSUE THREAD

**Issue by Matt-Esch** [uber/zanzibar#82]
The generate main.go files depend on "zanzibar-defaults.json". The main.go is generated with a hard coded relative file path. All files except the binary and the config directory will be removed, so this doesn't work. Either expect the defaults to be in the config directory itself, or pack the defaults into the binary.

**Comment by Raynos** [comment]
We should pack the defaults into the binary using go-bindata.

**Comment by Raynos** [comment]
This is done.
